# Using ``for`` loops to do repeated tasks

Repeated print/display to screen the numbers in this list called ``list_A``:

In [1]:
list_A = [1, 3, 5, 7, 9, 11, 13]

In [2]:
print(list_A[0])

1


In [3]:
print(list_A[1])

3


In [4]:
print(list_A[2])

5


In [5]:
print(list_A[-1])

13


In [6]:
print(list_A[6])

13


Here's one way to do it:

In [8]:
for index in range(len(list_A)):
    print([ index, list_A[index] ])

[0, 1]
[1, 3]
[2, 5]
[3, 7]
[4, 9]
[5, 11]
[6, 13]


Here's another way using the ``enumerate`` function in ``Python``:

In [9]:
for index, element in enumerate(list_A):
    print([index, element])

[0, 1]
[1, 3]
[2, 5]
[3, 7]
[4, 9]
[5, 11]
[6, 13]


Here's another example. We now work with a list of ``strings``.

In [10]:
list_B = [ "This", "workshop", "is", "so", "boring", ".", "I", 
           "feel", "like", "having", "Gamjatang", "tonight" ]

In [11]:
for idx, b in enumerate(list_B):
    print(b)

This
workshop
is
so
boring
.
I
feel
like
having
Gamjatang
tonight


A list can also be a combination of different elements, like this example:

In [13]:
import numpy as np

In [19]:
list_C = [ "I", "am", 12.3345, "a", "walrus", np.eye(3,3) ]

In [20]:
list_C

['I',
 'am',
 12.3345,
 'a',
 'walrus',
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])]

In [21]:
D = list_C[-1]

In [22]:
print(D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
